name: Go
on: [push]
jobs:
  
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      
    - name: say hi
      run: echo "hello code cafe"
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        go env
        go get -v -d ./...
    
    - name: Build
      run: go build -v .

    - name: test
      run: |
        echo $GOBIN
        export PATH=$PATH:$(go env GOPATH)/bin
        go get github.com/onsi/ginkgo/ginkgo
        ginkgo -r -v --trace
    
 
